Revert to previous travis build environment
An upgrade to a new Travis build environment [1] started casuing the
following spec failure on Ruby 2.1.5:

    1.1) Failure/Error: expect(r.out).to eq("")

    expected: ""
    got: "ERROR CODE: 1\nbundler: failed to load command: rails
    (/home/travis/build/mysociety/alaveteli/.bundle/ruby/2.1.0/bin/rails)
    NoMethodError: undefined method `activate_bin_path' for Gem:Module
    /home/travis/build/mysociety/alaveteli/.bundle/ruby/2.1.0/bin/rails:22:in
    `<top (required)>'\n"

I contacted Travis support [2] and they suggested adding
`group: deprecated` to the configuration, which seems to have worked.

I've followed up to see if there's a better long-term solution.

[1] https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/
[2] https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/EGtzVJyd3xg