Add note about updating gettext_i18n_rails
Versions above 0.9.4 cause the following error in various places:

     NoMethodError:
       undefined method `abstract_class?' for Object:Class
     # /home/vagrant/bundle/ruby/1.9.1/gems/gettext_i18n_rails-1.0.5/lib/gettext_i18n_rails/active_model/translation.rb:20:in `inheritance_tree_root'
     # /home/vagrant/bundle/ruby/1.9.1/gems/gettext_i18n_rails-1.0.5/lib/gettext_i18n_rails/active_model/translation.rb:13:in `gettext_translation_for_attribute_name'
     # /home/vagrant/bundle/ruby/1.9.1/gems/gettext_i18n_rails-1.0.5/lib/gettext_i18n_rails/active_model/translation.rb:5:in `human_attribute_name'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/column.rb:112:in `human_name'
     # ./app/models/concerns/admin_column.rb:15:in `block in for_admin_column'
     # ./app/models/concerns/admin_column.rb:14:in `each'
     # ./app/models/concerns/admin_column.rb:14:in `for_admin_column'
     # ./app/views/admin_public_body/_one_list.html.erb:14:in `block in _app_views_admin_public_body__one_list_html_erb___2698796816213731492_61721060'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22/lib/active_record/relation/delegation.rb:6:in `each'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22/lib/active_record/relation/delegation.rb:6:in `each'
     # ./app/views/admin_public_body/_one_list.html.erb:2:in `_app_views_admin_public_body__one_list_html_erb___2698796816213731492_61721060'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/template.rb:145:in `block in render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `block in instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/template.rb:143:in `render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `block in instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/partial_renderer.rb:237:in `render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/renderer.rb:41:in `render_partial'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/renderer.rb:15:in `render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/helpers/rendering_helper.rb:24:in `render'
     # ./app/views/admin_public_body/index.html.erb:39:in `_app_views_admin_public_body_index_html_erb___3939242291696623959_61579360'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/template.rb:145:in `block in render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `block in instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/template.rb:143:in `render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `block in instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:18:in `render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/renderer.rb:36:in `render_template'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_view/renderer/renderer.rb:17:in `render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:110:in `_render_template'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/streaming.rb:225:in `_render_template'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:103:in `render_to_body'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:88:in `render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/rendering.rb:16:in `render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/core_ext/benchmark.rb:5:in `ms'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:39:in `render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/abstract_controller/base.rb:167:in `process_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:591:in `block in _run__3978854059801661252__process_action__2743053394586074712__callbacks'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1310'
     # ./app/controllers/application_controller.rb:110:in `record_memory'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1310'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:579:in `_run__3978854059801661252__process_action__2743053394586074712__callbacks'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:405:in `__run_callback'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/abstract_controller/callbacks.rb:17:in `process_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `block in instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `instrument'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/activerecord-3.2.22/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/abstract_controller/base.rb:121:in `process'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:45:in `process'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/metal/testing.rb:17:in `process_with_new_base_test'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/test_case.rb:490:in `process'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/test_case.rb:54:in `process'
     # /home/vagrant/bundle/ruby/1.9.1/gems/actionpack-3.2.22/lib/action_controller/test_case.rb:407:in `get'
     # ./spec/controllers/admin_public_body_controller_spec.rb:8:in `block (2 levels) in <top (required)>'