Add a guard clause for receiving nil rather than {}
This method receives a value derived from controller parameters. With
the new parameter object in Rails 5, the result of trying to read a key
that is not present in params is nil rather than an empty Hash.

Fixes:

Failure/Error:
  attributes.each do |name, value|
    send("#{name}=", value)
  end

NoMethodError:
  undefined method `each' for nil:NilClass