Revert to old translation gem versions
These still work with Rails 5.0 so we don't need to upgrade them here.

Upgrading gettext_i18n_rails will mean introducing a new gettext API
which breaks our current rake tasks for updating and cleaning
translations:

https://github.com/grosser/gettext_i18n_rails/commit/d1b02f734f9e0c96de50d1a58e8170ce6ec457ac

Trying to use the new API without rewriting the rake tasks results in
errors such as:

LoadError: cannot load such file -- gettext/tools/task
NoMethodError: undefined method `msgmerge' for GetText:Module

There may also be changes to translation generation and workflow