Remove deprecated find_by_
This is a strange case – `find_by_` is not deprecated, but:

    PublicBodyHeading.find_by_name('New Heading')
    NoMethodError: undefined method `find_by_name' for PublicBodyHeading(id: integer, display_order: integer):Class
    from /home/vagrant/bundle/ruby/1.9.1/gems/activerecord-4.0.13/lib/active_record/dynamic_matchers.rb:22:in `method_missing'

I think this might be because we use `translates`, but don't have a `title` attribute on the model itself. I don't really know why this is, but in any case using `where` filters by the translated attribute (in the current locale), so fixes the problem here:

    PublicBodyHeading.where(:name => 'New Heading').first
      PublicBodyHeading Load (8.6ms)  SELECT "public_body_headings".* FROM "public_body_headings" INNER JOIN "public_body_heading_translations" ON "public_body_heading_translations"."public_body_heading_id" = "public_body_headings"."id" WHERE "public_body_heading_translations"."name" = 'New Heading' AND "public_body_heading_translations"."locale" = 'en' ORDER BY display_order ASC LIMIT 1