Clarify import_csv supported fields name attribute
https://github.com/mysociety/alaveteli/issues/1416

- Create a public body with name "Foobar"
- Now try to upload this CSV:

    #name,request_email,short_name
    Foobar Test,a@example.com,foobar

- The app raises the following exception:

    ERROR:  duplicate key value violates unique constraint
            "index_public_bodies_on_url_name"
    DETAIL:  Key (url_name)=(foobar) already exists.

---

The reason for this is that the CSV import looks up records by their
Name attribute. By attempting to rename the record, you're inadvertently
creating a new Public Body, since one with the name of "Foobar Test"
does not yet exist.