Destroy all associated incoming messages
Fixes https://github.com/mysociety/alaveteli/issues/5174.

Failing on CI using Rails 5 Gemfile with:

    1) When importing mail into the application should not produce any
       output and should return a 0 code on importing a plain email
       Got 1 failure and 1 other error:
       1.1) Failure/Error: expect(r.status).to eq(0)

	      expected: 0
		   got: 75

	      (compared using ==)
	    # ./spec/script/mailin_spec.rb:31:in `block (2 levels) in
	    <top (required)>'
       1.2) Failure/Error: incoming_message.destroy

	    NoMethodError:
	      undefined method `destroy' for nil:NilClass
	    # ./spec/script/mailin_spec.rb:39:in `block (2 levels) in
	    <top (required)>'

Try destroying all associated incoming messages so that we don't try to
call `#destroy` on `nil`. Perhaps Rails 5's `use_transactional_tests`
behaves slightly differently?