Refactor HasTagStringTag.find_by_tag
* Calls ARel on the parent class instead of directly on HasTagStringTag
* Removes Ruby collection and sorting
* Returns an ActiveRecord::Relation rather than an Array, so this is now
  chainable

    # Before
    ModelWithTag.find_by_tag('test').where(name: 'b').count
    # => NoMethodError: undefined method `where' for #<Array:0x0000000696ea50>

    # After
    ModelWithTag.find_by_tag('test').where(name: 'b').count
    # => 1