Patches for Debian Stretch
Adds imagemagick to packages file (backport of 98ac14a).

---

Renames ruby1.9*, php5-cli and libxslt to more modern package names.

---

Monkeypatch db:structure:dump

Monkeypatch to include the change in a PR [2] that removed deprecated -i
option from call to to pg_dump.

---

[1] https://stackoverflow.com/q/30671107/387558
[2] https://github.com/rails/rails/pull/21931

---

Backport 58f77d8c63fe4c602c851fcbc42544acdbba4f59.

Ensure sanitization of non UTF-8 subject lines

The current version of the mail gem returns `nil` when parsing
mails that have raw subject lines with non-UTF-8 characters in
them. However, the current mail master branch appears to return
the subject line encoded as SQL-ASCII without other error
indications.

Our principle is that all content stored in the database
should be UTF-8.

---

Backport 3eae763e99bde0c85a73f11aac1e41c1aee44988.

Convert non-UTF-8 bounce messages to UTF-8

The principle here is that everything in the database is for
human reading and should be UTF-8.

---

Don't cd to script dir to run load-mail-server-logs

Similar to 30fde410b2b28f372b2f9a3d9fa47177c39dd3fd.

Changing to the `script` dir makes this fail with:

    RuntimeError: path locale could not be found!

This is because gettext_i18n_rails tries to load
`APP_ROOT/script/locale` rather than `APP_ROOT/locale`.

---

Add test-unit to Gemfile

Hack for running Rails 3.2 on Ruby 2.3.5:

    $ bundle exec rails c
    /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require': Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (cannot load such file -- test/unit/testcase) (LoadError)
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/test_case.rb:2:in `<top (required)>'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22/lib/rails/console/app.rb:2:in `<top (required)>'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22/lib/rails/application.rb:312:in `initialize_console'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22/lib/rails/application.rb:152:in `load_console'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22/lib/rails/commands/console.rb:27:in `start'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22/lib/rails/commands/console.rb:8:in `start'
	    from /APP_ROOT/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22/lib/rails/commands.rb:41:in `<top (required)>'
	    from script/rails:6:in `require'
	    from script/rails:6:in `<main>'

---

Backport 663bb16df54870fcab0e15a6af36647991cdca9e.

Don't run service command as app user

This fails on Debian Stretch (and probably any other systemd-based OS)
when run as an app user as the service command just passes this to
systemctl which needs root privileges.

For now, just call the script directly as its the easiest thing to do to
fix the problem, and we do similar in the Capistrano deployment config.