Use sanitize_sql instead of sanitize
The ActiveRecord::Sanitization.sanitize method was removed in Rails 5.1

https://github.com/rails/rails/commit/d14a5defeb0c9f2972f90d83cb625beed8105d76#diff-0689d847b102af6667885c014182e48f

Raises the following error under Rails 5.1:

NoMethodError:
  undefined method `sanitize' for #<Class:…>

Apparently, this was in internal method that wasn't intended to be
called directly. More info: https://stackoverflow.com/a/44575173