Fix comparison bug in Statistics
Visiting the /statistics page was causing the following error:

    An ArgumentError occurred in statistics#index:

    comparison of Array with Array failed
    app/models/statistics.rb:136:in `sort'

    -------------------------------
    Backtrace:
    -------------------------------

    app/models/statistics.rb:136:in `sort'
    app/models/statistics.rb:136:in `by_week_to_today_with_noughts'
    app/controllers/statistics_controller.rb:9:in `index'
    app/controllers/application_controller.rb:108:in `record_memory'
    lib/strip_empty_sessions.rb:13:in `call'

I think what's happened is that since Rails 4,
InfoRequestEvent.count_of_hides_by_week now casts the String dates in to
Date instances. This is then passed to Statistics.by_week_to_today_with_noughts.

This means that we end up trying to do the following:

    require 'date'
    [[Date.parse('2016-03-30'), 1], ['2016-03-31', 2]].sort
    ArgumentError: comparison of Array with Array failed

* Update the specs so that input data contains Date instances instead of Strings
* Ensure Date instances are cast to Strings before we make try to sort