Fix Dataset::Value validation error
In Rails 6, ActiveModel's `validates_format_of` when not given a regexp
it will error with:
  TypeError: wrong argument type nil (expected Regexp)

This change switches to using an condition validation instead of using
the safe navigation operator.