Switch .tx/config to refer to transifex.com instead of transifex.net
The transifex-client version 0.9.1 rejects the transifex.net URL,
with the following error:

    CertificateError: hostname 'www.transifex.net' doesn't match
    either of '*.transifex.com', 'transifex.com'

... so update it to transifex.com.