Add Legislation#==
Allows us to compare `Legislation` instances for equality based its
semantics rather than the default `object_id`.

Without the changes to `include(have_attributes(…))` specs failed with
errors like:

    14) Legislation.for_public_body public body tagged as eir_only does
        not contains FOI legislation Failure/Error: other.to_sym ==
        to_sym

        NoMethodError: undefined method `to_sym' for
        #<RSpec::Matchers::BuiltIn::HaveAttributes:0x000055f97c029da8>
        Did you mean?  to_s # ./app/models/legislation.rb:75:in `==' #
        ./spec/models/legislation_spec.rb:93:in `block (4 levels) in
        <top (required)>'

Not clear if we're doing something weird here, whether there's an rspec
bug, or indeed a workaround.

Fixes https://github.com/mysociety/alaveteli/issues/6020